### PR TITLE
Replace gulp-webserver with gulp-connect. Fixes issue #195.

### PR DESCRIPTION
**Pull request by naknode**
This adheres issue #195 and successfully replaces said NPM package (which had 2 bad vulns). When I ran `npm audit`, it had no more security concerns.

```bash
➜  ~/code/oss/morgan-stanley/desktopJS git:(master) npm audit

                       === npm audit security report ===

found 0 vulnerabilities
 in 50045 scanned packages
```

---

### CODE REVIEW

**Comment by naknode** [comment]
@bingenito 	I hope this can fix it. A new PR with the commit (merged in one) and the covered by the DCO statement.

**Comment by bingenito** [comment]
@naknode Give me a day or so to work out future PR merge strategy on the repo now that we are dco.  Whether it should be merge vs squash, etc.  I had been doing squash and merge in the past.

**Comment by naknode** [comment]
Same here, it was always simple but DCO is better. Thanks for your speedy input.

**Comment by bingenito** [comment]
Fixes #195

**Pull request merged**
